name: SkyrimRPG
version: 0.2.6b-f3
authors: [dbizzzle, Technius, ThatBox]
main: me.dbizzzle.SkyrimRPG.SkyrimRPG
softdepends: [Spout]
commands:
   addspell:
      description: Adds a spell to the specified player
      usage: |
          /addspell <player> <spell>
   removespell:
      description: Removes a spell from the specified player
      usage: |
          /removespell <player> <spell>
   listspells:
      description: Lists all your spells
      usage: |
          /listspells [player]
   skyrimrpg:
      descrption: Displays info about SkyrimRPG
      aliases: srpg
      usage: |
         /srpg <action>
   skystats:
      description: Displays your skill level
      usage: |
         /stats <page>
   bindspell:
      description: Binds a spell to left/right hand
      usage: |
         /bindspell <left/right/both> <spell>
   addperk:
      description: Adds a perk to the specified player
      usage: |
         /addperk [player] <perk>
   removeperk:
      description: Removes a perk from the specified player
      usage: |
         /removeperk [player] <perk>
   perk:
      description: Shows the perk menu
      usage: |
         /perk <args>
permissions:
   skyrimrpg.*:
      Description: Gives all SkyrimRPG permissions
      Children:
         skyrimrpg.cheats.*: true
         skyrimrpg.user: true
         skyrimrpg.refresh: true
         skyrimrpg.reload: true
         skyrimrpg.nopickpocket: true
   skyrimrpg.admin:
      Description: Gives all SkyrimRPG admin permissions
      Children:
         skyrimrpg.refresh: true
         skyrimrpg.reload: true
         skyrimrpg.newversion: true
   skyrimrpg.cheats.*:
      Description: Allows you cheat on everything SkyrimRPG
      Children:
          skyrimrpg.cheats.spells: true
          skyrimrpg.cheats.perks: true
          skyrimrpg.setlevel.other: true
          skyrimrpg.spells.*: true
   skyrimrpg.cheats.spells:
      Description: Allows you to add and remove spells
      Children:
         skyrimrpg.addspell: true
         skyrimrpg.removespell: true
   skyrimrpg.cheats.perks:
      Description: Allows you to add and remove perks
      Children:
         skyrimrpg.addperk: true
         skyrimrpg.removeperk: true
   skyrimrpg.user:
      Description: Permission nodes for a "normal" user
      Children:
         skyrimrpg.listspells: true
         skyrimrpg.bindspell: true
   skyrimrpg.spells.*:
      Description: Allows a player to use all spells if spellPermissions is disabled
   skyrimrpg.addspell:
      Description: Give a player a spell.
   skyrimrpg.removespell:
      Description: Take a spell from a player.
   skyrimrpg.listspells: 
      Description: List spells or find out what spells another person has.
   skyrimrpg.bindspell:
      Description: Binds a spell to left/right/both hands
   skyrimrpg.refresh:
      Description: Refreshes the config
   skyrimrpg.reload:
      Description: Reloads the config
   skyrimrpg.setlevel:
      Description: Sets the level of the specified skill
   skyrimrpg.removeperk:
      Description: Removes a perk
   skyrimrpg.addperk:
      Description: Adds a perk
   skyrimrpg.setlevel.other:
      Description: Allows a player to set skill levels
      Children:
          skyrimrpg.setlevel: true