name: SkyrimRPG
version: 0.1.8b
authors: [dbizzzle, Technius, ThatBox]
main: me.dbizzzle.SkyrimRPG.SkyrimRPG
softdepends: [Spout]
commands:
   addspell:
      description: Adds a spell to the specified player
      usage: |
          /addspell <player> <spell>
   removespell:
      description: Removes a spell from the specified player
      usage: |
          /removespell <player> <spell>
   listspells:
      description: Lists all your spells
      usage: |
          /listspells [player]
   skyrimrpg:
      descrption: Displays info about SkyrimRPG
      aliases: srpg
      usage: |
         /srpg <action>
   skystats:
      description: Displays your skill level
      usage: |
         /stats <page>
   bindspell:
      description: Binds a spell to left/right hand
      usage: |
         /bindspell <left/right/both> <spell>
   addperk:
      description: Adds a perk to the specified player
      usage: |
         /addperk [player] <perk>
   removeperk:
      description: Removes a perk from the specified player
      usage: |
         /removeperk [player] <perk>
   perk:
      description: Shows the perk menu
      usage: |
         /perk <args>
permissions:
   skyrimrpg.*:
      Description: Implies all.
      Children:
         skyrimrpg.addspell: true
         skyrimrpg.removespell: true
         skyrimrpg.listspells: true
         skyrimrpg.bindspell: true
         skyrimrpg.setlevel: true
         skyrimrpg.removeperk: true
         skyrimrpg.addperk: true
   skyrimrpg.addspell:
      Description: Give a player a spell.
   skyrimrpg.removespell:
      Description: Take a spell from a player.
   skyrimrpg.listspells: 
      Description: List spells or find out what spells another person has.
   skyrimrpg.bindspell:
      Description: Binds a spell to left/right/both hands
   skyrimrpg.setlevel:
      Description: Sets the level of the specified skill
   skyrimrpg.removeperk:
      Description: Removes a perk
   skyrimrpg.addperk:
      Description: Adds a perk
   