name: SkyrimRPG
version: 0.1.3a
authors: [dbizzzle, Technius]
main: me.dbizzzle.SkyrimRPG.SkyrimRPG
commands:
   addspell:
      description: Adds a spell to the specified player
      usage: |
          /addspell <player> <spell>
   removespell:
      description: Removes a spell from the specified player
      usage: |
          /removespell <player> <spell>
   listspells:
      description: Lists all your spells
      usage: |
          /listspells [player]
   skyrimrpg:
      descrption: Displays info about SkyrimRPG
      aliases: srpg
      usage: |
         /srpg <action>
   skystats:
      description: Displays your skill level
      usage: |
         /stats <page>
   bindspell:
      description: Binds a spell to left/right hand
      usage: |
         /bindspell <left/right/both> <spell>
permissions:
   SkyrimRPG.*:
      Description: Implies all.
      Children:
         SkyrimRPG.addspell: true
         SkyrimRPG.removespell: true
         SkyrimRPG.listspells: true
   SkyrimRPG.addspell:
      Description: Give a player a spell.
   SkyrimRPG.removespell:
      Description: Take a spell from a player.
   SkyrimRPG.listspells: 
      Description: List spells or find out what spells another person has.
   SkyrimRPG.bindspell:
      Description: Binds a spell to left/right/both hands